Extra visualization removed from overlap tooltip, ref issue #36
* If we choose to have these, they should be replaced by the same svg system as in the overlap images themselves

* IMPORTANT!  There is a bug in the tooltip code:
"TypeError: t is not a function"
At index.html, profile Michael Doe, size S, chest tooltip